### ISSUE TITLE
Adding sugar

### ISSUE THREAD

**Issue by nickmessing** [vuejs/babel-preset-vue#1]
I think we could add sugar transforms to this preset as a complex preset. Here's draft [release notes](https://gist.github.com/nickmessing/27b10c32925645416c5b4c3bc26df797). It's 100% reverse compatible. The only thing that could be potentially affected is:
```js
const A = () => <h1>Hello</h1>
```
But since we use `this.$createElement` this syntax is not likely to be used anywhere.

@yyx990803, @egoist, what do you think?

**Comment by yyx990803** [comment]
Looks good to me!

**Comment by nickmessing** [comment]
@yyx990803, I'll make a PR after I solve nickmessing/babel-plugin-jsx-v-model#1

**Comment by egoist** [comment]
Just added @yyx990803 to this package (and babel-preset-vue-app) on npm ✅
