### ISSUE TITLE
prevent auto convert HTML escape characters

### ISSUE THREAD

**Issue by even-today** [vuejs/babel-preset-vue#10]
For Example:
in parent:
`
render(){
  return (
    <div>abc &lt; </div>
  )
}
`

in child
`
this.$slots.default // we have "abc <"
`

Is there any way to prevent auto-converting `&lt;` to `<` ?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
